services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=secretpgpwd
    ports:
      - 5432:5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
      - ./ssl/server.crt:/tmp/server.crt:ro
      - ./ssl/server.key:/tmp/server.key:ro
      - ./ssl/root.crt:/tmp/root.crt:ro
